name: Release please version bump

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Branch main check
        run: |
          if [[ "${GITHUB_REF}" != "refs/head/main" ]]; then
            echo "Workflow is not invoked from main branch."
            exit 1
          fi

      - uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump verion in package.json and Release-As
        run: |
          npm --no-git-tag-version version minor
          bumped=$(jq -r '.version' package.json)
          git add .
          git commit -m "chore: bump version to $bumped" -m "Release-As: $bumped-rc.0" -n
          git push
